---
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/fedecoraglio/microservices_with_spring
          searchPaths: common/config-data
        # "native" is used when the native profile is active, for local tests with a classpath repo:
        native:
          searchLocations: classpath:offline-repository/
server:
  port: 8001